name: muslim_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  flutter_svg: 1.1.0
  sliding_up_panel: 2.0.0+1
  file_picker: 4.6.1
  http: 0.13.4
  audio_waveforms: 
    path: ./audio_waveform
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/test.mp3
    - assets/images/
    - assets/icons/
    - assets/icons/navbar/
    - assets/icons/time/
  uses-material-design: true

